/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as PlayIndexImport } from "./routes/play/index";

// Create Virtual Routes

const FiorLazyImport = createFileRoute("/fior")();
const IndexLazyImport = createFileRoute("/")();

// Create/Update Routes

const FiorLazyRoute = FiorLazyImport.update({
  id: "/fior",
  path: "/fior",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/fior.lazy").then((d) => d.Route));

const IndexLazyRoute = IndexLazyImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

const PlayIndexRoute = PlayIndexImport.update({
  id: "/play/",
  path: "/play/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/play/index.lazy").then((d) => d.Route));

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/fior": {
      id: "/fior";
      path: "/fior";
      fullPath: "/fior";
      preLoaderRoute: typeof FiorLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/play/": {
      id: "/play/";
      path: "/play";
      fullPath: "/play";
      preLoaderRoute: typeof PlayIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexLazyRoute;
  "/fior": typeof FiorLazyRoute;
  "/play": typeof PlayIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexLazyRoute;
  "/fior": typeof FiorLazyRoute;
  "/play": typeof PlayIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexLazyRoute;
  "/fior": typeof FiorLazyRoute;
  "/play/": typeof PlayIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/fior" | "/play";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/fior" | "/play";
  id: "__root__" | "/" | "/fior" | "/play/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute;
  FiorLazyRoute: typeof FiorLazyRoute;
  PlayIndexRoute: typeof PlayIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  FiorLazyRoute: FiorLazyRoute,
  PlayIndexRoute: PlayIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/fior",
        "/play/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/fior": {
      "filePath": "fior.lazy.tsx"
    },
    "/play/": {
      "filePath": "play/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
