// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
import { highlight } from "./pql-highlight";
const spec_Name = {
  __proto__: null,
  select: 14,
  from: 20,
  where: 22,
  order: 38,
  by: 40,
};
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "%vQ]QPOOOOQO'#Cq'#CqQ]QPOOObQPO'#CaOOQO-E6o-E6oOpQPO'#CrOuQPO'#CdOuQPO'#CdO!ZQPO,58{OOQO,59^,59^OOQO-E6p-E6pO!`QPO,59OO!tQPO1G.gO#]QPO7+$RO#kQPO<<GmO#pQPO<<GmO$RQPOAN=XO$aQPO'#CjOOQO'#Ci'#CiO$kQPOAN=XO%`QPO'#ChOOQOG22sG22sO#pQPO'#CsO%zQPO,59UOOQO,59U,59UO&SQPO,59UO&^QPOG22sOOQO'#Cn'#CnO#pQPO,59SO&cQPO,59_OOQO-E6q-E6qOOQO1G.p1G.pO&mQPO1G.pO$RQPOLD(_O&uQPO1G.nOOQO7+$[7+$[OOQO!$'Ky!$'Ky",
  stateData:
    "']~OPOSQOSROS~OVRO~OUVOXTOjWOYWP~OUXO~OXTOYWXVWXZWXcWXhWX~OY[O~OXTOYWaVWaZWacWahWa~OUVOXTOj]OVWPZWPcWPhWP~OZ_Oc^OVTqhTq~Od`O~OUbO_bO`bOabOkaO~OUVOXTOVWPhWP~OXfOlhO~P#pOcjOVT!RhT!Rm]Xn]Xo]Xp]Xq]Xr]Xs]Xt]X~OmkOnkOokOpkOqkOrkOskOtkO~OXfOloO~OXfOloO~P%`OdqO~OXgalga~P%`OXfOlsO~OV[ic[ih[iX[il[i~P%`OaU~",
  goto: "#YhPPPPPiPPmPPPy!R!_PPP!ePP!k!q#OTPOQQWRQ][Qe`RtqUbaflRc_Qd_QiaQmfRrlXb_aflXldimrQQORSQWUR[`qSYUZRZVQgaSngpRpi",
  nodeNames:
    "⚠ Spaces NewLine Comment pql Select Name select NameArray , from where Predicate Value Tuple String Number ConstBool Cmp order by",
  maxTerm: 36,
  propSources: [highlight],
  skippedNodes: [0, 1, 2, 3],
  repeatNodeCount: 3,
  tokenData:
    "-P~RsXY#`YZ$TZ[#`]^$Tpq#`qr$Yrs$evw%Vxy%byz%gz{%l|}%q}!O%v!O!P&e!Q!['z!^!_(t!_!`)R!`!a)^!c!})k#R#S)k#T#Y)k#Y#Z)y#Z#h)k#h#i+z#i#o)k#p#q,t$f$g#`#BY#BZ#`$IS$I_#`$I|$I}$T$I}$JO$T$JT$JU#`$KV$KW#`&FU&FV#`?HT?HU#`~#eYP~XY#`Z[#`pq#`$f$g#`#BY#BZ#`$IS$I_#`$JT$JU#`$KV$KW#`&FU&FV#`?HT?HU#`~$YOQ~~$]P!_!`$`~$eOr~~$hUOY$eZr$ers$zs;'S$e;'S;=`%P<%lO$e~%PO_~~%SP;=`<%l$e~%YPvw%]~%bOs~~%gOk~~%lOl~~%qOj~~%vOX~~%yP}!O%|~&RSR~OY%|Z;'S%|;'S;=`&_<%lO%|~&bP;=`<%l%|~&hP!Q![&k~&nQ!Q![&t#R#S&t~&yS`~!Q![&t!g!h'V#R#S&t#X#Y'V~'YS{|'f}!O'f!Q!['o#R#S'o~'iQ!Q!['o#R#S'o~'tQ`~!Q!['o#R#S'o~'}R!Q![(W#R#S(W#b#c(o~(]U`~!O!P&e!Q![(W!g!h'V#R#S(W#X#Y'V#b#c(o~(tO`~~(yPm~!_!`(|~)ROo~~)UP!_!`)X~)^Oq~~)cPn~!_!`)f~)kOp~~)pRU~!c!})k#R#S)k#T#o)k~*OSU~!c!})k#R#S)k#T#U*[#U#o)k~*aTU~!c!})k#R#S)k#T#`)k#`#a*p#a#o)k~*uTU~!c!})k#R#S)k#T#g)k#g#h+U#h#o)k~+ZTU~!c!})k#R#S)k#T#X)k#X#Y+j#Y#o)k~+qRa~U~!c!})k#R#S)k#T#o)k~,PTU~!c!})k#R#S)k#T#f)k#f#g,`#g#o)k~,eTU~!c!})k#R#S)k#T#i)k#i#j+U#j#o)k~,wP#p#q,z~-POt~",
  tokenizers: [0],
  topRules: { pql: [0, 4] },
  specialized: [
    { term: 6, get: (value: keyof typeof spec_Name) => spec_Name[value] || -1 },
  ],
  tokenPrec: 286,
});
