[workspace]
members = ["core", "shuttle"]
resolver = "2"
package.edition = "2021"
package.version = "0.0.1"
package.authors = ["4lineclear"]
package.license = "MIT"

[workspace.dependencies]
libsql = { version = "0.6", default-features = false, features = [
	"core",
	"remote",
] }
